# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_remove_fbreach_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbreach',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
