# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-04 09:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_fbreach_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 4, 9, 5, 7, 671000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techprofile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 4, 9, 5, 11, 670000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopteam',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 4, 9, 5, 18, 746000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
