# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-04 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_auto_20180104_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='technexId',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
