# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-04 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_notifications_technexid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='token',
            field=models.TextField(unique=True),
        ),
    ]
