# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-24 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_auto_20180105_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetpayment',
            name='row',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
